name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - uses: actions/checkout@v3
          
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 216725
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 216725+scala-steward-erikerlandson[bot]@users.noreply.github.com
          author-name: scala-steward-erikerlandson[bot]
          github-app-id: 216725
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
          repos-file: 'repos.md'
